[package]
name = "codec_sv2"
version = "2.0.0"
authors = ["The Stratum V2 Developers"]
edition = "2018"
readme = "README.md"
description = "Sv2 data format"
documentation = "https://docs.rs/codec_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[dependencies]
framing_sv2 = { path = "../../../protocols/v2/framing-sv2" }
noise_sv2 = { path = "../../../protocols/v2/noise-sv2", default-features = false, optional = true }
binary_sv2 = { path = "../../../protocols/v2/binary-sv2" }
const_sv2 = { path = "../../../protocols/v2/const-sv2"}
buffer_sv2 = { path = "../../../utils/buffer"}
rand = { version = "0.8.5", default-features = false }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
key-utils = { path = "../../../utils/key-utils" }

[features]
default = ["std"]
std = ["noise_sv2?/std", "rand/std", "rand/std_rng", "dep:tracing"]
with_buffer_pool = ["framing_sv2/with_buffer_pool"]

[package.metadata.docs.rs]
features = ["with_buffer_pool", "noise_sv2", "std"]
