# This workflow is used to create a new release with a binary distribution or SRI roles
# If the binary releases fails due to not having tags, force run the `autoversion` workflow
# on the main branch and merge the resulting PR to create the tags and move them to the main branch.

name: Release Binaries

on:
  # Manually run by going to "Actions/Release" in Github and running the workflow
  workflow_dispatch:

jobs:
  release_solo_demand_all_in_one:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile Native
        run: cargo build --release --locked --manifest-path=roles/demand-solo-all-in-one/Cargo.toml

      - name: Install aarch64-apple-darwin target
        if: matrix.os == 'macos-latest'
        run: rustup target add aarch64-apple-darwin

      - name: Compile MacOS ARM64
        if: matrix.os == 'macos-latest'
        run: cargo build --release --locked --manifest-path=roles/demand-solo-all-in-one/Cargo.toml --target=aarch64-apple-darwin

      - name: Upload Linux x86-64 binaries to release
        if: matrix.os == 'ubuntu-20.04'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: roles/target/release/demand-solo-all-in-one
          asset_name: demand_all_in_one_sv2-x86_64-linux-gnu
          tag: 0.1.1

      - name: Upload MacOS x86-64 binaries to release
        if: matrix.os == 'macos-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: roles/target/release/demand-solo-all-in-one
          asset_name: demand_all_in_one_sv2-x86_64-apple-darwin
          tag: 0.1.1

      - name: Upload MacOS ARM64 binaries to release
        if: matrix.os == 'macos-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: roles/target/aarch64-apple-darwin/release/demand-solo-all-in-one
          asset_name: demand_all_in_one_sv2-aarch64-apple-darwin
          tag: 0.1.1
